language: php

php:
  - 5.6
  - 7.0

before_script:
  - travis_retry composer install --prefer-dist

script:
  - vendor/bin/run-tests -C

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
