language: php
php:
    - 7.1
    - 7.2
    - master

os:
  - linux
  - osx

matrix:
  allow_failures:
    - php: master

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest --prefer-dist"

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
  - if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS; fi
  - if [[ "$DEPENDENCIES" = 'low' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS --prefer-lowest; fi

script:
  - composer test

jobs:
    include:
        -   stage: Static Analysis
            php: 7.2
            script:
                - composer phpstan

        -   stage: Code Coverage
            php: 7.2
            script:
                - vendor/bin/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./app
            after_script:
                - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
                - php php-coveralls.phar --verbose --config tests/.coveralls.yml

    allow_failures:
        -   stage: Code Coverage

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
